<?php

/**
 * @var \Shellpea\NewModule\Block\Display $block
 */

echo $block->sayHello();
echo "";
?>

<form action="<?php echo $block->getFormAction();?>  method="post">

    <label for="name">Name:</label><br>
    <input type="text" id="fname" name="name"><br>
    <label for="email">Email:</label><br>
    <input type="email" id="lname" name="email" placeholder="exmple@example">
    <label for="message_text">What’s on your mind?</label><br>
    <textarea name="message_text" placeholder=" "></textarea>
    <?= $escaper->escapeHtml($block->getStorePhoneNumber()) ?>
    <br>
    <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>

</form>






