<?php

/**
 * @var \Shellpea\NewModule\Block\Display $block
 */

echo $block->sayHello();
echo "";
?>

<form action="<?php echo $block->getFormAction();?>  method="post">

    <label for="fname">Name:</label><br>
    <input type="text" id="fname" name="fname"><br>
    <label for="lname">Email:</label><br>
    <input type="email" id="lname" name="lname" placeholder="exmple@example">
    <label for="lname">What’s on your mind?</label><br>
    <textarea placeholder=" "></textarea>
    <?= $escaper->escapeHtml($block->getStorePhoneNumber()) ?>
    <br>
    <button type="submit" class="action submit primary" title="Save"><span><?= $block->escapeHtmlAttr(__('Save')) ?></span></button>

</form>






